services:
  backend:
    image: ${DOCKER_REGISTRY-}appwithreact
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: "http://+:80"
      #PRODUCION_BASE: ${sql_connection}
      #JWT_SECRET: ${jwt_secret}
    ports:
      - "5000:80"
  client:
    build:
      context: ./App/ClientApp
      dockerfile: Dockerfile
    ports:
      - "5003:3000"
    depends_on:
      - backend
  proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data 
volumes:
 pgdata:

